export const SPORT_POSITIONS: Record<string, string[]> = {
  soccer: [
    "Goalkeeper",
    "Center Back",
    "Left Back",
    "Right Back",
    "Defensive Midfielder",
    "Central Midfielder",
    "Attacking Midfielder",
    "Left Wing",
    "Right Wing",
    "Striker",
    "Forward",
  ],
  baseball: [
    "Pitcher",
    "Catcher",
    "First Base",
    "Second Base",
    "Third Base",
    "Shortstop",
    "Left Field",
    "Center Field",
    "Right Field",
    "Designated Hitter",
  ],
  softball: [
    "Pitcher",
    "Catcher",
    "First Base",
    "Second Base",
    "Third Base",
    "Shortstop",
    "Left Field",
    "Center Field",
    "Right Field",
    "Designated Player",
  ],
  basketball: [
    "Point Guard",
    "Shooting Guard",
    "Small Forward",
    "Power Forward",
    "Center",
  ],
  volleyball: [
    "Setter",
    "Outside Hitter",
    "Middle Blocker",
    "Opposite Hitter",
    "Libero",
    "Defensive Specialist",
  ],
  hockey: [
    "Goalie",
    "Left Defense",
    "Right Defense",
    "Center",
    "Left Wing",
    "Right Wing",
  ],
  lacrosse: [
    "Goalie",
    "Close Defense",
    "Long Stick Midfielder",
    "Defensive Midfielder",
    "Midfielder",
    "Attack",
    "Face-Off Specialist",
  ],
};
