/**
 * Seed St. Louis area sports venues into the database.
 *
 * Usage:
 *   pnpm seed:venues
 *
 * Requires NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in .env.local
 * (Service role key bypasses RLS for seeding)
 */

import { createClient } from "@supabase/supabase-js";
import { config } from "dotenv";

config({ path: ".env.local" });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !serviceRoleKey) {
  console.error(
    "Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local"
  );
  process.exit(1);
}

const supabase = createClient(supabaseUrl, serviceRoleKey);

type Venue = {
  name: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  lat: number | null;
  lng: number | null;
  parking_notes: string | null;
  field_count: number | null;
  sport_types: string[];
};

const venues: Venue[] = [
  // ============================================================
  // MAJOR SOCCER / LACROSSE COMPLEXES
  // ============================================================
  {
    name: "Lou Fusz Soccer Complex",
    address: "2155 Creve Coeur Mill Rd",
    city: "Maryland Heights",
    state: "MO",
    zip: "63146",
    lat: 38.6914,
    lng: -90.4518,
    parking_notes: "Multiple lots surrounding fields. Lot fills up during tournaments.",
    field_count: 12,
    sport_types: ["soccer", "lacrosse"],
  },
  {
    name: "World Wide Technology Soccer Park",
    address: "900 N Duchesne Dr",
    city: "St. Charles",
    state: "MO",
    zip: "63301",
    lat: 38.7942,
    lng: -90.4943,
    parking_notes: "Large main lot off Duchesne Dr.",
    field_count: 16,
    sport_types: ["soccer", "lacrosse"],
  },
  {
    name: "Creve Coeur Park Soccer Complex",
    address: "2185 Creve Coeur Mill Rd",
    city: "Maryland Heights",
    state: "MO",
    zip: "63043",
    lat: 38.6908,
    lng: -90.4525,
    parking_notes: "Parking along Creve Coeur Mill Rd. Walk from lot to fields.",
    field_count: 13,
    sport_types: ["soccer"],
  },
  {
    name: "Sportport Complex",
    address: "1 Sportport Dr",
    city: "Maryland Heights",
    state: "MO",
    zip: "63043",
    lat: 38.7155,
    lng: -90.4358,
    parking_notes: "Dedicated parking lot adjacent to fields.",
    field_count: 12,
    sport_types: ["soccer", "lacrosse", "hockey"],
  },
  {
    name: "Chesterfield Valley Athletic Complex (CVAC)",
    address: "17925 N Outer 40 Rd",
    city: "Chesterfield",
    state: "MO",
    zip: "63005",
    lat: 38.6441,
    lng: -90.5953,
    parking_notes: "Multiple large parking lots. Enter from N Outer 40 Rd.",
    field_count: 31,
    sport_types: ["soccer", "baseball", "softball", "lacrosse", "volleyball"],
  },
  {
    name: "Slyman Bros SLYSA Complex",
    address: "5800 Mexico Rd",
    city: "St. Peters",
    state: "MO",
    zip: "63376",
    lat: 38.7651,
    lng: -90.5877,
    parking_notes: "Parking lot off Mexico Rd.",
    field_count: 8,
    sport_types: ["soccer"],
  },
  {
    name: "CYC South Complex",
    address: "4711 Mattis Rd",
    city: "St. Louis",
    state: "MO",
    zip: "63128",
    lat: 38.5193,
    lng: -90.3505,
    parking_notes: null,
    field_count: 6,
    sport_types: ["soccer", "baseball"],
  },
  {
    name: "Vetta Sports — Concord",
    address: "2900 Hwy K",
    city: "O'Fallon",
    state: "MO",
    zip: "63368",
    lat: 38.7361,
    lng: -90.7178,
    parking_notes: "Large parking lot on site.",
    field_count: 4,
    sport_types: ["soccer", "lacrosse", "volleyball", "basketball"],
  },

  // ============================================================
  // CITY OF ST. LOUIS PARKS
  // ============================================================
  {
    name: "Tower Grove Park",
    address: "4256 Magnolia Ave",
    city: "St. Louis",
    state: "MO",
    zip: "63110",
    lat: 38.6047,
    lng: -90.2562,
    parking_notes: "Street parking along Magnolia Ave and internal park roads.",
    field_count: 4,
    sport_types: ["soccer", "baseball", "softball"],
  },
  {
    name: "Carondelet Park",
    address: "930 Holly Hills Ave",
    city: "St. Louis",
    state: "MO",
    zip: "63111",
    lat: 38.5687,
    lng: -90.2635,
    parking_notes: "Parking lots near Loughborough entrance and rec complex.",
    field_count: 6,
    sport_types: ["soccer", "baseball", "softball", "basketball"],
  },
  {
    name: "Forest Park — Aviation Fields",
    address: "5595 Grand Dr",
    city: "St. Louis",
    state: "MO",
    zip: "63112",
    lat: 38.6339,
    lng: -90.2842,
    parking_notes: "Park along Grand Dr near the aviation fields area.",
    field_count: 4,
    sport_types: ["soccer", "lacrosse", "baseball"],
  },
  {
    name: "Forest Park — Steinberg Rink Area",
    address: "400 Jefferson Dr",
    city: "St. Louis",
    state: "MO",
    zip: "63110",
    lat: 38.6285,
    lng: -90.2797,
    parking_notes: "Parking near Steinberg Rink and along Jefferson Dr.",
    field_count: 2,
    sport_types: ["soccer", "hockey"],
  },
  {
    name: "Francis Park",
    address: "5399 Donovan Ave",
    city: "St. Louis",
    state: "MO",
    zip: "63109",
    lat: 38.5878,
    lng: -90.2954,
    parking_notes: "Street parking along Donovan Ave and Nottingham Ave.",
    field_count: 2,
    sport_types: ["soccer", "baseball"],
  },
  {
    name: "Willmore Park",
    address: "4777 Jamieson Ave",
    city: "St. Louis",
    state: "MO",
    zip: "63109",
    lat: 38.5880,
    lng: -90.3035,
    parking_notes: "Parking along Jamieson Ave.",
    field_count: 3,
    sport_types: ["soccer", "baseball", "softball"],
  },
  {
    name: "Sherman Park",
    address: "1200 N Union Blvd",
    city: "St. Louis",
    state: "MO",
    zip: "63113",
    lat: 38.6578,
    lng: -90.2430,
    parking_notes: null,
    field_count: 2,
    sport_types: ["baseball", "basketball"],
  },
  {
    name: "O'Fallon Park",
    address: "4100 W Florissant Ave",
    city: "St. Louis",
    state: "MO",
    zip: "63115",
    lat: 38.6751,
    lng: -90.2403,
    parking_notes: "Parking lots off W Florissant Ave.",
    field_count: 3,
    sport_types: ["baseball", "basketball", "soccer"],
  },
  {
    name: "Fairground Park",
    address: "3800 Natural Bridge Ave",
    city: "St. Louis",
    state: "MO",
    zip: "63107",
    lat: 38.6672,
    lng: -90.2293,
    parking_notes: "Multiple entrances with street parking.",
    field_count: 2,
    sport_types: ["baseball", "basketball"],
  },
  {
    name: "Sublette Park",
    address: "5701 Sublette Ave",
    city: "St. Louis",
    state: "MO",
    zip: "63109",
    lat: 38.5840,
    lng: -90.2983,
    parking_notes: "Street parking on Sublette Ave.",
    field_count: 2,
    sport_types: ["soccer", "baseball"],
  },
  {
    name: "Ivory Perry Park",
    address: "6201 Page Blvd",
    city: "St. Louis",
    state: "MO",
    zip: "63112",
    lat: 38.6524,
    lng: -90.2698,
    parking_notes: null,
    field_count: 2,
    sport_types: ["baseball", "basketball"],
  },

  // ============================================================
  // ST. LOUIS COUNTY PARKS
  // ============================================================
  {
    name: "Queeny Park",
    address: "550 Weidman Rd",
    city: "Ballwin",
    state: "MO",
    zip: "63011",
    lat: 38.5921,
    lng: -90.5398,
    parking_notes: "Main lot off Weidman Rd. Overflow lot near dog park.",
    field_count: 4,
    sport_types: ["soccer", "lacrosse", "baseball"],
  },
  {
    name: "Tilles Park",
    address: "9551 Litzsinger Rd",
    city: "St. Louis",
    state: "MO",
    zip: "63124",
    lat: 38.6211,
    lng: -90.3547,
    parking_notes: "Parking lots off Litzsinger Rd.",
    field_count: 4,
    sport_types: ["soccer", "baseball", "softball", "lacrosse"],
  },
  {
    name: "Suson Park",
    address: "6073 Wells Rd",
    city: "St. Louis",
    state: "MO",
    zip: "63128",
    lat: 38.5140,
    lng: -90.3523,
    parking_notes: "Parking near athletic fields off Wells Rd.",
    field_count: 4,
    sport_types: ["soccer", "baseball", "softball"],
  },
  {
    name: "Jefferson Barracks Park",
    address: "345 North Rd",
    city: "St. Louis",
    state: "MO",
    zip: "63125",
    lat: 38.4935,
    lng: -90.2798,
    parking_notes: "Multiple lots throughout the park.",
    field_count: 6,
    sport_types: ["soccer", "baseball", "softball"],
  },
  {
    name: "Creve Coeur Lake Memorial Park",
    address: "2100 Creve Coeur Mill Rd",
    city: "Maryland Heights",
    state: "MO",
    zip: "63043",
    lat: 38.6925,
    lng: -90.4520,
    parking_notes: "Multiple lots. Use Creve Coeur Mill Rd entrance for fields.",
    field_count: 3,
    sport_types: ["soccer", "lacrosse"],
  },
  {
    name: "Lyons Park",
    address: "839 Swallow Dr",
    city: "Kirkwood",
    state: "MO",
    zip: "63122",
    lat: 38.5719,
    lng: -90.4168,
    parking_notes: "Small lot off Swallow Dr.",
    field_count: 2,
    sport_types: ["soccer", "baseball"],
  },
  {
    name: "Vago Park",
    address: "1000 Austin Dr",
    city: "Des Peres",
    state: "MO",
    zip: "63131",
    lat: 38.6030,
    lng: -90.4455,
    parking_notes: null,
    field_count: 2,
    sport_types: ["soccer", "baseball"],
  },
  {
    name: "Ackerman Park",
    address: "1293 Ackerman Rd",
    city: "Kirkwood",
    state: "MO",
    zip: "63122",
    lat: 38.5640,
    lng: -90.4085,
    parking_notes: "Lot off Ackerman Rd. Fills up for tournaments.",
    field_count: 2,
    sport_types: ["baseball", "softball"],
  },
  {
    name: "Sylvan Springs Park",
    address: "13725 Manchester Rd",
    city: "Manchester",
    state: "MO",
    zip: "63011",
    lat: 38.5798,
    lng: -90.5268,
    parking_notes: "Enter off Manchester Rd.",
    field_count: 3,
    sport_types: ["soccer", "baseball"],
  },
  {
    name: "Babler State Park — Sports Fields",
    address: "800 Guy Park Dr",
    city: "Wildwood",
    state: "MO",
    zip: "63005",
    lat: 38.6092,
    lng: -90.6791,
    parking_notes: "Follow signs to athletic area. Gravel lot.",
    field_count: 2,
    sport_types: ["soccer", "lacrosse"],
  },

  // ============================================================
  // RECREATION CENTERS & INDOOR FACILITIES
  // ============================================================
  {
    name: "Brentwood Community Center",
    address: "2505 S Brentwood Blvd",
    city: "Brentwood",
    state: "MO",
    zip: "63144",
    lat: 38.6112,
    lng: -90.3491,
    parking_notes: "Parking lot behind community center.",
    field_count: 2,
    sport_types: ["soccer", "baseball", "basketball", "volleyball"],
  },
  {
    name: "Kirkwood Community Center",
    address: "111 S Geyer Rd",
    city: "Kirkwood",
    state: "MO",
    zip: "63122",
    lat: 38.5834,
    lng: -90.4089,
    parking_notes: "Parking lot and garage adjacent.",
    field_count: null,
    sport_types: ["basketball", "volleyball"],
  },
  {
    name: "Des Peres Lodge & Recreation",
    address: "1050 Des Peres Rd",
    city: "Des Peres",
    state: "MO",
    zip: "63131",
    lat: 38.6010,
    lng: -90.4323,
    parking_notes: "Large lot next to lodge.",
    field_count: null,
    sport_types: ["basketball", "volleyball"],
  },
  {
    name: "Webster Groves Recreation Complex",
    address: "33 E Glendale Rd",
    city: "Webster Groves",
    state: "MO",
    zip: "63119",
    lat: 38.5918,
    lng: -90.3562,
    parking_notes: null,
    field_count: 2,
    sport_types: ["soccer", "baseball", "basketball"],
  },
  {
    name: "Affton Athletic Association",
    address: "9999 Mackenzie Rd",
    city: "Affton",
    state: "MO",
    zip: "63123",
    lat: 38.5498,
    lng: -90.3301,
    parking_notes: "Lot off Mackenzie Rd.",
    field_count: 4,
    sport_types: ["baseball", "softball"],
  },
  {
    name: "St. Peters Rec-Plex",
    address: "5200 Mexico Rd",
    city: "St. Peters",
    state: "MO",
    zip: "63376",
    lat: 38.7650,
    lng: -90.5920,
    parking_notes: "Very large parking lot.",
    field_count: null,
    sport_types: ["hockey", "basketball", "volleyball", "soccer"],
  },
  {
    name: "Vetta Sports — Manchester",
    address: "575 Weidman Rd",
    city: "Ballwin",
    state: "MO",
    zip: "63011",
    lat: 38.5910,
    lng: -90.5410,
    parking_notes: "Dedicated parking lot.",
    field_count: 3,
    sport_types: ["soccer", "lacrosse", "volleyball", "basketball"],
  },
  {
    name: "Carondelet Park Rec Complex (YMCA)",
    address: "930 Holly Hills Ave",
    city: "St. Louis",
    state: "MO",
    zip: "63111",
    lat: 38.5690,
    lng: -90.2645,
    parking_notes: "Parking at rec complex entrance on Holly Hills.",
    field_count: null,
    sport_types: ["basketball", "volleyball"],
  },

  // ============================================================
  // SUBURBAN COMPLEXES
  // ============================================================
  {
    name: "O'Fallon Sports Park",
    address: "4375 Crusher Dr",
    city: "O'Fallon",
    state: "MO",
    zip: "63368",
    lat: 38.7362,
    lng: -90.7017,
    parking_notes: "Multiple lots around the park. Enter off Crusher Dr.",
    field_count: 10,
    sport_types: ["soccer", "baseball", "softball", "lacrosse"],
  },
  {
    name: "Founders Park Sports Complex",
    address: "1 Founders Park Dr",
    city: "Lake Saint Louis",
    state: "MO",
    zip: "63367",
    lat: 38.7575,
    lng: -90.7855,
    parking_notes: "Large lot off Founders Park Dr.",
    field_count: 8,
    sport_types: ["soccer", "baseball", "softball", "lacrosse"],
  },
  {
    name: "St. Louis Athletic Center",
    address: "1000 Heatherly Dr",
    city: "Fenton",
    state: "MO",
    zip: "63026",
    lat: 38.5205,
    lng: -90.4515,
    parking_notes: "Parking lot in front of building.",
    field_count: null,
    sport_types: ["basketball", "volleyball"],
  },
  {
    name: "Norm West Park",
    address: "1024 Bryan Rd",
    city: "O'Fallon",
    state: "MO",
    zip: "63366",
    lat: 38.7842,
    lng: -90.7120,
    parking_notes: "Lot off Bryan Rd.",
    field_count: 4,
    sport_types: ["soccer", "baseball", "softball"],
  },
  {
    name: "Heritage Park",
    address: "1 Heritage Dr",
    city: "O'Fallon",
    state: "MO",
    zip: "63368",
    lat: 38.7440,
    lng: -90.7260,
    parking_notes: null,
    field_count: 4,
    sport_types: ["soccer", "baseball"],
  },
  {
    name: "Mattingly Sports Complex",
    address: "18500 Chesterfield Airport Rd",
    city: "Chesterfield",
    state: "MO",
    zip: "63005",
    lat: 38.6505,
    lng: -90.6302,
    parking_notes: "Large lot on site.",
    field_count: null,
    sport_types: ["baseball", "softball", "basketball", "volleyball"],
  },
  {
    name: "Youth Activity Park",
    address: "900 City Park Dr",
    city: "O'Fallon",
    state: "IL",
    zip: "62269",
    lat: 38.6083,
    lng: -89.9255,
    parking_notes: "Lot off City Park Dr.",
    field_count: 8,
    sport_types: ["soccer", "lacrosse", "baseball"],
  },
  {
    name: "Belleville Sports Complex",
    address: "2800 W Main St",
    city: "Belleville",
    state: "IL",
    zip: "62226",
    lat: 38.5210,
    lng: -89.9980,
    parking_notes: "Multiple lots around complex.",
    field_count: 6,
    sport_types: ["soccer", "baseball", "softball"],
  },

  // ============================================================
  // POPULAR SCHOOL / MULTI-USE FACILITIES
  // ============================================================
  {
    name: "CBC (Christian Brothers College) Fields",
    address: "1850 De La Salle Dr",
    city: "Town and Country",
    state: "MO",
    zip: "63141",
    lat: 38.6315,
    lng: -90.4732,
    parking_notes: "School parking lots. Follow event signage.",
    field_count: 3,
    sport_types: ["soccer", "lacrosse", "baseball"],
  },
  {
    name: "MICDS Athletic Fields",
    address: "101 N Warson Rd",
    city: "Ladue",
    state: "MO",
    zip: "63124",
    lat: 38.6360,
    lng: -90.3700,
    parking_notes: "Visitor parking off Warson Rd.",
    field_count: 4,
    sport_types: ["soccer", "lacrosse", "baseball", "hockey"],
  },
  {
    name: "Principia School Fields",
    address: "13201 Clayton Rd",
    city: "Town and Country",
    state: "MO",
    zip: "63131",
    lat: 38.6258,
    lng: -90.4851,
    parking_notes: "Visitor lot on Clayton Rd.",
    field_count: 3,
    sport_types: ["soccer", "lacrosse", "baseball"],
  },
  {
    name: "Kirkwood High School Fields",
    address: "801 W Essex Ave",
    city: "Kirkwood",
    state: "MO",
    zip: "63122",
    lat: 38.5764,
    lng: -90.4200,
    parking_notes: "School lot off Essex Ave.",
    field_count: 3,
    sport_types: ["soccer", "baseball", "lacrosse"],
  },
  {
    name: "Webster Groves High School Fields",
    address: "100 Selma Ave",
    city: "Webster Groves",
    state: "MO",
    zip: "63119",
    lat: 38.5870,
    lng: -90.3530,
    parking_notes: "Parking off Selma Ave or Lockwood Ave.",
    field_count: 3,
    sport_types: ["soccer", "baseball", "lacrosse"],
  },
  {
    name: "Lafayette High School Fields",
    address: "17050 Clayton Rd",
    city: "Wildwood",
    state: "MO",
    zip: "63011",
    lat: 38.6137,
    lng: -90.5732,
    parking_notes: "Main school lot.",
    field_count: 3,
    sport_types: ["soccer", "lacrosse", "baseball"],
  },
];

async function seed() {
  console.log(`Seeding ${venues.length} St. Louis area venues...`);

  // Use upsert with name as conflict target to be idempotent
  const { data, error } = await supabase
    .from("venues")
    .upsert(venues, { onConflict: "name" })
    .select("id");

  if (error) {
    console.error("Error seeding venues:", error.message);
    process.exit(1);
  }

  console.log(`Done! Seeded ${data?.length ?? 0} venues.`);
}

seed();
